name: sellers_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - images/

fonts:
  - family: Bebas
    fonts:
      - asset: assets/fonts/BebasNeue-Regular.ttf
  - family: Lobster
    fonts:
      - asset: assets/fonts/Lobster-Regular.ttf
  - family: Signatra
    fonts:
      - asset: assets/fonts/Signatra.ttf
  - family: VarelaRound
    fonts:
      - asset: assets/fonts/VarelaRound-Regular.ttf